"use client";

import { Activity, ShieldCheck, Video, Clock } from "lucide-react";

export default function AdminPage() {
    // Mock data for the recordings, since actual files would be generated by the Antigravity sub-agent
    const recordings = [
        { id: 1, llm: "ChatGPT", vertical: "Project Management", time: "10 mins ago", status: "Success", file: "#" },
        { id: 2, llm: "Perplexity", vertical: "CRM", time: "15 mins ago", status: "Success", file: "#" },
        { id: 3, llm: "Gemini", vertical: "Design Tools", time: "22 mins ago", status: "Success", file: "#" },
    ];

    return (
        <div className="p-8 max-w-5xl mx-auto space-y-8">
            <div className="flex items-center gap-3 mb-8">
                <ShieldCheck className="w-8 h-8 text-emerald-400" />
                <h1 className="text-3xl font-bold text-white font-mono tracking-tight">Agentic Health Dashboard</h1>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-2xl">
                    <div className="flex items-center gap-3 text-slate-400 mb-2">
                        <Activity className="w-5 h-5 text-blue-400" />
                        <h3 className="font-semibold text-sm uppercase tracking-wider">Pipeline Status</h3>
                    </div>
                    <p className="text-2xl font-bold text-emerald-400 flex items-center gap-2">
                        <span className="w-3 h-3 rounded-full bg-emerald-400 animate-pulse"></span>
                        Operational
                    </p>
                </div>

                <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-2xl">
                    <div className="flex items-center gap-3 text-slate-400 mb-2">
                        <Clock className="w-5 h-5 text-purple-400" />
                        <h3 className="font-semibold text-sm uppercase tracking-wider">Last Run</h3>
                    </div>
                    <p className="text-2xl font-bold text-white">Today, 12:00 AM</p>
                </div>

                <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-2xl">
                    <div className="flex items-center gap-3 text-slate-400 mb-2">
                        <Video className="w-5 h-5 text-red-400" />
                        <h3 className="font-semibold text-sm uppercase tracking-wider">Recordings</h3>
                    </div>
                    <p className="text-2xl font-bold text-white">30 / 30 Passed</p>
                </div>
            </div>

            <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden shadow-2xl mt-8">
                <div className="p-6 border-b border-slate-800 bg-slate-800/50">
                    <h2 className="text-xl font-bold text-white flex items-center gap-2">
                        <Video className="w-5 h-5" /> Recent Scraper Execution Videos
                    </h2>
                    <p className="text-slate-400 text-sm mt-1">Review 10-second replays of the Antigravity Browser Agent to verify no CAPTCHAs were hit.</p>
                </div>
                <div className="divide-y divide-slate-800">
                    {recordings.map((rec) => (
                        <div key={rec.id} className="p-6 flex items-center justify-between hover:bg-slate-800/30 transition-colors">
                            <div className="flex items-center gap-4">
                                <div className="w-12 h-12 bg-slate-800 rounded-lg flex items-center justify-center">
                                    <Video className="w-6 h-6 text-slate-400" />
                                </div>
                                <div>
                                    <h4 className="font-bold text-white">{rec.llm} - {rec.vertical}</h4>
                                    <p className="text-sm text-slate-400">{rec.time}</p>
                                </div>
                            </div>
                            <div className="flex items-center gap-4">
                                <span className="px-3 py-1 bg-emerald-400/10 text-emerald-400 rounded-full text-sm font-medium border border-emerald-400/20">
                                    {rec.status}
                                </span>
                                <button className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-white text-sm font-semibold rounded-lg transition-colors border border-slate-700">
                                    Watch Replay
                                </button>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
}
