"use client";

import { useState } from "react";
import { Vertical, AuditReport } from "@/lib/types";
import { FileText, Download, Loader } from "lucide-react";

const VERTICALS: Vertical[] = [
    "Project Management", "CRM", "Cloud Storage", "AI Writing", "Design Tools",
];

const BRANDS_BY_VERTICAL: Record<Vertical, string[]> = {
    "Project Management": ["Notion", "Asana", "Monday.com", "ClickUp", "Jira"],
    "CRM": ["Salesforce", "HubSpot", "Pipedrive", "Zoho CRM", "Freshsales"],
    "Cloud Storage": ["Google Drive", "Dropbox", "Box", "OneDrive", "pCloud"],
    "AI Writing": ["Jasper", "Copy.ai", "Writesonic", "Rytr", "Anyword"],
    "Design Tools": ["Figma", "Canva", "Adobe XD", "Sketch", "Framer"],
};

export default function AuditDownload() {
    const [vertical, setVertical] = useState<Vertical>("Project Management");
    const [brand, setBrand] = useState("Notion");
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    async function downloadPDF() {
        setLoading(true);
        setError(null);
        try {
            // 1. Fetch the audit JSON from the server
            const res = await fetch(
                `/api/audit?brand=${encodeURIComponent(brand)}&vertical=${encodeURIComponent(vertical)}`
            );
            if (!res.ok) {
                const err = await res.json().catch(() => ({ error: "Unknown error" }));
                throw new Error(err.error || `Server error ${res.status}`);
            }
            const audit: AuditReport = await res.json();

            // 2. Build the PDF entirely in the browser using jsPDF
            const { jsPDF } = await import("jspdf");
            const doc = new jsPDF({ unit: "pt", format: "a4" });
            const PAGE_W = doc.internal.pageSize.getWidth();
            const MARGIN = 50;
            const CONTENT_W = PAGE_W - MARGIN * 2;
            let y = 60;

            const needsPage = (extra = 0) => {
                if (y + extra > doc.internal.pageSize.getHeight() - 60) {
                    doc.addPage();
                    y = 60;
                }
            };

            // ── Cover ────────────────────────────────────────────────
            doc.setFont("helvetica", "bold");
            doc.setFontSize(26);
            doc.setTextColor(26, 26, 46);
            doc.text("AI Visibility Audit Report", PAGE_W / 2, y, { align: "center" });
            y += 30;

            doc.setFont("helvetica", "normal");
            doc.setFontSize(14);
            doc.setTextColor(74, 78, 105);
            doc.text(`${audit.brand} · ${audit.vertical}`, PAGE_W / 2, y, { align: "center" });
            y += 18;

            doc.setFontSize(9);
            doc.setTextColor(136, 136, 136);
            const genDate = new Date(audit.generatedAt).toLocaleDateString("en-US", {
                year: "numeric", month: "long", day: "numeric",
            });
            doc.text(
                `Generated by Ghost Recon · ${genDate}`,
                PAGE_W / 2, y, { align: "center" }
            );
            y += 36;

            // ── Section helper ───────────────────────────────────────
            const section = (title: string) => {
                needsPage(40);
                y += 10;
                doc.setFont("helvetica", "bold");
                doc.setFontSize(13);
                doc.setTextColor(26, 26, 46);
                doc.text(title, MARGIN, y);
                y += 4;
                doc.setDrawColor(220, 220, 220);
                doc.line(MARGIN, y, PAGE_W - MARGIN, y);
                y += 14;
            };

            const labelRow = (lbl: string, val: string, color?: [number, number, number]) => {
                needsPage(30);
                doc.setFont("helvetica", "bold");
                doc.setFontSize(10);
                doc.setTextColor(85, 85, 85);
                doc.text(`${lbl}: `, MARGIN, y);
                const lw = doc.getTextWidth(`${lbl}: `);
                doc.setFont("helvetica", "normal");
                if (color) doc.setTextColor(...color);
                else doc.setTextColor(26, 26, 46);
                doc.text(val, MARGIN + lw, y);
                y += 18;
            };

            const bodyText = (text: string) => {
                needsPage(40);
                doc.setFont("helvetica", "normal");
                doc.setFontSize(10);
                doc.setTextColor(51, 51, 51);
                const lines = doc.splitTextToSize(text, CONTENT_W);
                lines.forEach((line: string) => {
                    needsPage(14);
                    doc.text(line, MARGIN, y);
                    y += 14;
                });
                y += 6;
            };

            // ── Executive Summary ────────────────────────────────────
            section("Executive Summary");
            bodyText(audit.executiveSummary);

            // ── AVS Scores ───────────────────────────────────────────
            section("AI Visibility Score (AVS)");
            labelRow("AVS (Flat)", `${audit.avs} / 100`);
            labelRow("Weighted AVS", `${audit.weightedAvs} / 100`);
            const deltaVal = audit.avsDelta >= 0 ? `+${audit.avsDelta}` : `${audit.avsDelta}`;
            labelRow("AVS Trend Delta", deltaVal, audit.avsDelta >= 0 ? [42, 157, 143] : [230, 57, 70]);
            labelRow("Tracked Share of Voice", `${audit.tsov}%`);

            // ── LLM Breakdown ────────────────────────────────────────
            section("LLM-Specific AVS Breakdown");
            labelRow("ChatGPT", `${audit.avsBreakdown.chatgpt}`);
            labelRow("Gemini", `${audit.avsBreakdown.gemini}`);
            labelRow("Perplexity", `${audit.avsBreakdown.perplexity}`);
            needsPage(14);
            doc.setFont("helvetica", "italic");
            doc.setFontSize(8);
            doc.setTextColor(136, 136, 136);
            doc.text(
                "Note: Tracked SOV sums to 100 within the monitored brand set — not total market share.",
                MARGIN, y
            );
            y += 20;

            // ── Narrative Intelligence ───────────────────────────────
            section("AI Narrative Intelligence");
            labelRow("Positioning Category", audit.narrative.positioningCategory);
            labelRow("Authority Strength", `${audit.authorityStrengthScore} / 100`);
            labelRow("Signature Adjectives", audit.narrative.signatureAdjectives.join("  ·  "));
            needsPage(14);
            doc.setFont("helvetica", "bold");
            doc.setFontSize(9);
            doc.setTextColor(136, 136, 136);
            doc.text("NARRATIVE SUMMARY", MARGIN, y);
            y += 12;
            bodyText(audit.narrative.narrativeSummary);

            if (audit.narrative.differentiationSignals?.length) {
                needsPage(14);
                doc.setFont("helvetica", "bold");
                doc.setFontSize(9);
                doc.setTextColor(136, 136, 136);
                doc.text("DIFFERENTIATION SIGNALS", MARGIN, y);
                y += 12;
                audit.narrative.differentiationSignals.forEach((sig: string) => bodyText(`• ${sig}`));
            }

            // ── Narrative Drift ──────────────────────────────────────
            if (audit.narrative.narrativeShift) {
                section("Narrative Drift");
                labelRow("What Changed", audit.narrative.narrativeShift);
                if (audit.narrative.emergingThemes?.length) {
                    labelRow("Emerging Themes", audit.narrative.emergingThemes.join("  ·  "), [42, 157, 143]);
                }
                if (audit.narrative.lostThemes?.length) {
                    labelRow("Lost Themes", audit.narrative.lostThemes.join("  ·  "), [230, 57, 70]);
                }
            }

            // ── Competitor Gap ───────────────────────────────────────
            if (audit.topCompetitorGap) {
                const gap = audit.topCompetitorGap;
                section(`Competitor Gap: ${audit.brand} vs ${gap.brandB}`);
                const avsD = gap.avsDifference >= 0 ? `+${gap.avsDifference.toFixed(1)}` : `${gap.avsDifference.toFixed(1)}`;
                const sovD = gap.sovDifference >= 0 ? `+${gap.sovDifference.toFixed(1)}%` : `${gap.sovDifference.toFixed(1)}%`;
                labelRow("AVS Difference", avsD, gap.avsDifference >= 0 ? [42, 157, 143] : [230, 57, 70]);
                labelRow("SOV Difference", sovD, gap.sovDifference >= 0 ? [42, 157, 143] : [230, 57, 70]);
                if (gap.llmsCompetitorLeads?.length) {
                    labelRow("LLMs Where Competitor Leads",
                        gap.llmsCompetitorLeads.join(", "), [230, 57, 70]);
                }
                needsPage(14);
                doc.setFont("helvetica", "bold");
                doc.setFontSize(9);
                doc.setTextColor(136, 136, 136);
                doc.text("ANALYSIS", MARGIN, y);
                y += 12;
                bodyText(gap.summary);
            }

            // ── Strategic Recommendations ────────────────────────────
            section("Strategic Recommendations (Gemini-Generated)");
            audit.recommendations.forEach((rec: string, i: number) => {
                needsPage(30);
                doc.setFont("helvetica", "bold");
                doc.setFontSize(10);
                doc.setTextColor(74, 78, 105);
                doc.text(`${i + 1}.`, MARGIN, y);
                doc.setFont("helvetica", "normal");
                doc.setTextColor(51, 51, 51);
                const lines = doc.splitTextToSize(rec, CONTENT_W - 16);
                lines.forEach((line: string, li: number) => {
                    needsPage(14);
                    doc.text(line, MARGIN + 16, y + (li === 0 ? 0 : 0));
                    if (li !== lines.length - 1) y += 14;
                });
                y += 20;
            });

            // ── Footer ───────────────────────────────────────────────
            const totalPages = (doc.internal as { getNumberOfPages: () => number }).getNumberOfPages();
            for (let p = 1; p <= totalPages; p++) {
                doc.setPage(p);
                const pageH = doc.internal.pageSize.getHeight();
                doc.setFont("helvetica", "normal");
                doc.setFontSize(8);
                doc.setTextColor(170, 170, 170);
                doc.text(
                    "Ghost Recon — AI Recommendation Intelligence Platform · Confidential",
                    PAGE_W / 2, pageH - 20, { align: "center" }
                );
                doc.text(`Page ${p} of ${totalPages}`, PAGE_W - MARGIN, pageH - 20, { align: "right" });
            }

            // 3. Trigger download
            const filename = `ghost-recon-audit-${brand.toLowerCase().replace(/\s+/g, "-")}.pdf`;
            doc.save(filename);
        } catch (e) {
            setError(e instanceof Error ? e.message : "Download failed");
        } finally {
            setLoading(false);
        }
    }

    return (
        <section className="audit-download">
            <div className="audit-header">
                <FileText size={18} />
                <h2>AI Visibility Audit</h2>
                <span className="audit-tag">PDF Report</span>
            </div>

            <p className="audit-desc">
                Generate a full audit report including AVS, Share of Voice, Competitor Gap, Narrative
                Intelligence, and Gemini-generated strategic recommendations.
            </p>

            <div className="audit-controls">
                <div className="audit-field">
                    <label>Vertical</label>
                    <select
                        value={vertical}
                        onChange={(e) => {
                            setVertical(e.target.value as Vertical);
                            setBrand(BRANDS_BY_VERTICAL[e.target.value as Vertical][0]);
                        }}
                    >
                        {VERTICALS.map((v) => <option key={v}>{v}</option>)}
                    </select>
                </div>
                <div className="audit-field">
                    <label>Brand</label>
                    <select value={brand} onChange={(e) => setBrand(e.target.value)}>
                        {BRANDS_BY_VERTICAL[vertical].map((b) => <option key={b}>{b}</option>)}
                    </select>
                </div>
                <button className="audit-btn" onClick={downloadPDF} disabled={loading}>
                    {loading ? (
                        <><Loader size={16} className="spin" /> Generating...</>
                    ) : (
                        <><Download size={16} /> Download Audit PDF</>
                    )}
                </button>
            </div>

            {error && <div className="audit-error">⚠ {error}</div>}

            <div className="audit-inclusions">
                <span className="ai-item">✓ Executive Summary</span>
                <span className="ai-item">✓ AVS + Trend Delta</span>
                <span className="ai-item">✓ Share of Voice</span>
                <span className="ai-item">✓ LLM Breakdown</span>
                <span className="ai-item">✓ Competitor Gap</span>
                <span className="ai-item">✓ Narrative Analysis</span>
                <span className="ai-item">✓ Strategic Recommendations</span>
            </div>
        </section>
    );
}
